### ISSUE TITLE
Can't import usocket

### ISSUE THREAD

**Issue by vidjuheffex** [ktakashi/r6rs-usocket#1]
steps I took:
1) run `make` in the root
2) create a new file in "test" dir
3) add library dirs the way the testing-setup script has them:
```
#!r6rs
(library-directories
 (cons
  (string-append (path-parent (current-directory)) "/lib/")
  (cons
   (string-append (path-parent (current-directory)) "/deps/pffi/src")
   (cons
    (string-append (path-parent (current-directory)) "/deps/psystem/lib")
         (library-directories)))))

(import (rnrs)
	      (pffi)
	      (usocket))
```
I get the following message:
```
Exception: multiple definitions for null-pointer? in body (library (usocket srfi pffi) (export socket? make-client-socket make-server-socket socket-input-port socket-output-port ...) (import (rnrs) (pffi) (psystem libc) (psystem os) (usocket consts)) (define-condition-type &socket &error make-socket-error socket-error? (socket socket-error-socket)) (define-record-type base-socket (fields (...))) ...) at line 33, char 1 of /home/jules/Code/geiser/scheme/chez/libs/usockets/lib/usocket/srfi/pffi.sls
Type (debug) to enter the debugger.
>
```

I'm guessing its the multiple definitions of `null-pointer?` across the srfi and the seperate pffi dep. Not sure where I am going wrong.

**Comment by ktakashi** [comment]
Thank you for the report!
I believe this is a bug on `(pffi)` which I've recently updated to export `null-pointer?`. I'll check.

**Comment by vidjuheffex** [comment]
Thanks!

**Comment by ktakashi** [comment]
Hi @vidjuheffex,
Could you tell me which implementation you are using?
I've tried on Chez and Sagittarius but couldn't get the error.

**Comment by vidjuheffex** [comment]
I'm using chez on Ubuntu,

**Comment by vidjuheffex** [comment]
is it my library paths? Am I missing one?

**Comment by ktakashi** [comment]
No, you are not missing anything. The commit removes the duplicated definition in `(usocket srfi pffi)`. So, it should resolve the issue.

**Comment by vidjuheffex** [comment]
Ohh! I didn't see you made a commit. My bad! Thank you.
